/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as AlbumsAlbumIdReviewRouteImport } from './routes/albums/$albumId/review'
import { Route as AlbumsAlbumIdPhotosRouteImport } from './routes/albums/$albumId/photos'
import { Route as AlbumsAlbumIdCompleteRouteImport } from './routes/albums/$albumId/complete'
import { Route as AlbumsAlbumIdArrangeRouteImport } from './routes/albums/$albumId/arrange'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdReviewRoute = AlbumsAlbumIdReviewRouteImport.update({
  id: '/albums/$albumId/review',
  path: '/albums/$albumId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdPhotosRoute = AlbumsAlbumIdPhotosRouteImport.update({
  id: '/albums/$albumId/photos',
  path: '/albums/$albumId/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdCompleteRoute = AlbumsAlbumIdCompleteRouteImport.update({
  id: '/albums/$albumId/complete',
  path: '/albums/$albumId/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdArrangeRoute = AlbumsAlbumIdArrangeRouteImport.update({
  id: '/albums/$albumId/arrange',
  path: '/albums/$albumId/arrange',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create/': typeof CreateIndexRoute
  '/albums/$albumId/arrange': typeof AlbumsAlbumIdArrangeRoute
  '/albums/$albumId/complete': typeof AlbumsAlbumIdCompleteRoute
  '/albums/$albumId/photos': typeof AlbumsAlbumIdPhotosRoute
  '/albums/$albumId/review': typeof AlbumsAlbumIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateIndexRoute
  '/albums/$albumId/arrange': typeof AlbumsAlbumIdArrangeRoute
  '/albums/$albumId/complete': typeof AlbumsAlbumIdCompleteRoute
  '/albums/$albumId/photos': typeof AlbumsAlbumIdPhotosRoute
  '/albums/$albumId/review': typeof AlbumsAlbumIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create/': typeof CreateIndexRoute
  '/albums/$albumId/arrange': typeof AlbumsAlbumIdArrangeRoute
  '/albums/$albumId/complete': typeof AlbumsAlbumIdCompleteRoute
  '/albums/$albumId/photos': typeof AlbumsAlbumIdPhotosRoute
  '/albums/$albumId/review': typeof AlbumsAlbumIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create/'
    | '/albums/$albumId/arrange'
    | '/albums/$albumId/complete'
    | '/albums/$albumId/photos'
    | '/albums/$albumId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/albums/$albumId/arrange'
    | '/albums/$albumId/complete'
    | '/albums/$albumId/photos'
    | '/albums/$albumId/review'
  id:
    | '__root__'
    | '/'
    | '/create/'
    | '/albums/$albumId/arrange'
    | '/albums/$albumId/complete'
    | '/albums/$albumId/photos'
    | '/albums/$albumId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateIndexRoute: typeof CreateIndexRoute
  AlbumsAlbumIdArrangeRoute: typeof AlbumsAlbumIdArrangeRoute
  AlbumsAlbumIdCompleteRoute: typeof AlbumsAlbumIdCompleteRoute
  AlbumsAlbumIdPhotosRoute: typeof AlbumsAlbumIdPhotosRoute
  AlbumsAlbumIdReviewRoute: typeof AlbumsAlbumIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId/review': {
      id: '/albums/$albumId/review'
      path: '/albums/$albumId/review'
      fullPath: '/albums/$albumId/review'
      preLoaderRoute: typeof AlbumsAlbumIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId/photos': {
      id: '/albums/$albumId/photos'
      path: '/albums/$albumId/photos'
      fullPath: '/albums/$albumId/photos'
      preLoaderRoute: typeof AlbumsAlbumIdPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId/complete': {
      id: '/albums/$albumId/complete'
      path: '/albums/$albumId/complete'
      fullPath: '/albums/$albumId/complete'
      preLoaderRoute: typeof AlbumsAlbumIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId/arrange': {
      id: '/albums/$albumId/arrange'
      path: '/albums/$albumId/arrange'
      fullPath: '/albums/$albumId/arrange'
      preLoaderRoute: typeof AlbumsAlbumIdArrangeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateIndexRoute: CreateIndexRoute,
  AlbumsAlbumIdArrangeRoute: AlbumsAlbumIdArrangeRoute,
  AlbumsAlbumIdCompleteRoute: AlbumsAlbumIdCompleteRoute,
  AlbumsAlbumIdPhotosRoute: AlbumsAlbumIdPhotosRoute,
  AlbumsAlbumIdReviewRoute: AlbumsAlbumIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
