/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as AlbumsAlbumIdReviewRouteImport } from './routes/albums/$albumId/review'
import { Route as AlbumsAlbumIdPhotosRouteImport } from './routes/albums/$albumId/photos'
import { Route as AlbumsAlbumIdCompleteRouteImport } from './routes/albums/$albumId/complete'
import { Route as AlbumsAlbumIdArrangeRouteImport } from './routes/albums/$albumId/arrange'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdReviewRoute = AlbumsAlbumIdReviewRouteImport.update({
  id: '/albums/$albumId/review',
  path: '/albums/$albumId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdPhotosRoute = AlbumsAlbumIdPhotosRouteImport.update({
  id: '/albums/$albumId/photos',
  path: '/albums/$albumId/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdCompleteRoute = AlbumsAlbumIdCompleteRouteImport.update({
  id: '/albums/$albumId/complete',
  path: '/albums/$albumId/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdArrangeRoute = AlbumsAlbumIdArrangeRouteImport.update({
  id: '/albums/$albumId/arrange',
  path: '/albums/$albumId/arrange',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/create/': typeof CreateIndexRoute
  '/albums/$albumId/arrange': typeof AlbumsAlbumIdArrangeRoute
  '/albums/$albumId/complete': typeof AlbumsAlbumIdCompleteRoute
  '/albums/$albumId/photos': typeof AlbumsAlbumIdPhotosRoute
  '/albums/$albumId/review': typeof AlbumsAlbumIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/create': typeof CreateIndexRoute
  '/albums/$albumId/arrange': typeof AlbumsAlbumIdArrangeRoute
  '/albums/$albumId/complete': typeof AlbumsAlbumIdCompleteRoute
  '/albums/$albumId/photos': typeof AlbumsAlbumIdPhotosRoute
  '/albums/$albumId/review': typeof AlbumsAlbumIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/create/': typeof CreateIndexRoute
  '/albums/$albumId/arrange': typeof AlbumsAlbumIdArrangeRoute
  '/albums/$albumId/complete': typeof AlbumsAlbumIdCompleteRoute
  '/albums/$albumId/photos': typeof AlbumsAlbumIdPhotosRoute
  '/albums/$albumId/review': typeof AlbumsAlbumIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/create/'
    | '/albums/$albumId/arrange'
    | '/albums/$albumId/complete'
    | '/albums/$albumId/photos'
    | '/albums/$albumId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/create'
    | '/albums/$albumId/arrange'
    | '/albums/$albumId/complete'
    | '/albums/$albumId/photos'
    | '/albums/$albumId/review'
  id:
    | '__root__'
    | '/'
    | '/confirm'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/create/'
    | '/albums/$albumId/arrange'
    | '/albums/$albumId/complete'
    | '/albums/$albumId/photos'
    | '/albums/$albumId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmRoute: typeof ConfirmRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  CreateIndexRoute: typeof CreateIndexRoute
  AlbumsAlbumIdArrangeRoute: typeof AlbumsAlbumIdArrangeRoute
  AlbumsAlbumIdCompleteRoute: typeof AlbumsAlbumIdCompleteRoute
  AlbumsAlbumIdPhotosRoute: typeof AlbumsAlbumIdPhotosRoute
  AlbumsAlbumIdReviewRoute: typeof AlbumsAlbumIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId/review': {
      id: '/albums/$albumId/review'
      path: '/albums/$albumId/review'
      fullPath: '/albums/$albumId/review'
      preLoaderRoute: typeof AlbumsAlbumIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId/photos': {
      id: '/albums/$albumId/photos'
      path: '/albums/$albumId/photos'
      fullPath: '/albums/$albumId/photos'
      preLoaderRoute: typeof AlbumsAlbumIdPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId/complete': {
      id: '/albums/$albumId/complete'
      path: '/albums/$albumId/complete'
      fullPath: '/albums/$albumId/complete'
      preLoaderRoute: typeof AlbumsAlbumIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId/arrange': {
      id: '/albums/$albumId/arrange'
      path: '/albums/$albumId/arrange'
      fullPath: '/albums/$albumId/arrange'
      preLoaderRoute: typeof AlbumsAlbumIdArrangeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmRoute: ConfirmRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  CreateIndexRoute: CreateIndexRoute,
  AlbumsAlbumIdArrangeRoute: AlbumsAlbumIdArrangeRoute,
  AlbumsAlbumIdCompleteRoute: AlbumsAlbumIdCompleteRoute,
  AlbumsAlbumIdPhotosRoute: AlbumsAlbumIdPhotosRoute,
  AlbumsAlbumIdReviewRoute: AlbumsAlbumIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
